# Generated by Django 4.2.6 on 2023-12-10 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('usu_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('usu_apellido', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=128)),
                ('usu_numdoc', models.PositiveBigIntegerField(null=True)),
                ('usu_fechanacimiento', models.DateField(null=True)),
                ('usu_fecharegistro', models.DateField(auto_now_add=True)),
                ('usu_telefono', models.PositiveBigIntegerField(null=True)),
                ('usu_metododepago', models.CharField(max_length=30, null=True)),
                ('usu_ubicacion', models.CharField(max_length=30, null=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_tienda', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metodop',
            fields=[
                ('met_id', models.AutoField(primary_key=True, serialize=False)),
                ('met_titular', models.CharField(max_length=50)),
                ('met_numero', models.PositiveBigIntegerField(unique=True)),
                ('met_fechaexpira', models.DateField()),
                ('met_cvv', models.PositiveBigIntegerField()),
                ('met_fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('state', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('sed_id', models.AutoField(primary_key=True, serialize=False)),
                ('sed_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('sed_banner', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('sed_emailtienda', models.CharField(blank=True, max_length=30, unique=True)),
                ('sed_teltienda', models.CharField(blank=True, max_length=10, null=True)),
                ('sed_ubicacion', models.CharField(blank=True, max_length=30, null=True)),
                ('sed_nomdueno', models.CharField(blank=True, max_length=30, null=True)),
                ('sed_apedueno', models.CharField(blank=True, max_length=30, null=True)),
                ('sed_teldueno', models.CharField(blank=True, max_length=10, null=True)),
                ('sed_docdueno', models.CharField(blank=True, max_length=10, null=True)),
                ('sed_emaildueno', models.CharField(blank=True, max_length=30, null=True)),
                ('sed_banco', models.CharField(choices=[('Bancolombia', 'Bancolombia'), ('Avevillas', 'Avevillas')], default=None, max_length=30, null=True)),
                ('sed_tipcuenta', models.CharField(choices=[('ahorro', 'ahorro'), ('corriente', 'corriente')], default=None, max_length=30, null=True)),
                ('sed_nomtitular', models.CharField(blank=True, max_length=30, null=True)),
                ('sed_numcuentabancaria', models.CharField(blank=True, max_length=20, null=True)),
                ('sed_Nit', models.CharField(blank=True, max_length=9, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=30)),
                ('pro_especificacion', models.TextField(max_length=200)),
                ('pro_foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('pro_precio', models.IntegerField()),
                ('pro_tipo', models.CharField(choices=[('vegetariano', 'vegetariano'), ('vegano', 'vegano'), ('vegano y vegetariano', 'vegano y vegetariano')], default=None, max_length=20)),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api_ecove.categorias')),
                ('sed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api_ecove.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('direccion_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_ecove.metodop')),
                ('productos', models.ManyToManyField(through='api_ecove.DetalleOrden', to='api_ecove.productos')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='api_ecove.tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('hlun_aper1', models.TimeField()),
                ('hlun_cie1', models.TimeField()),
                ('hlun_aper2', models.TimeField(null=True)),
                ('hlun_cie2', models.TimeField(null=True)),
                ('hmar_aper1', models.TimeField()),
                ('hmar_cie1', models.TimeField()),
                ('hmar_aper2', models.TimeField(null=True)),
                ('hmar_cie2', models.TimeField(null=True)),
                ('hmie_aper1', models.TimeField()),
                ('hmie_cie1', models.TimeField()),
                ('hmie_aper2', models.TimeField(null=True)),
                ('hmie_cie2', models.TimeField(null=True)),
                ('hjue_aper1', models.TimeField()),
                ('hjue_cie1', models.TimeField()),
                ('hjue_aper2', models.TimeField(null=True)),
                ('hjue_cie2', models.TimeField(null=True)),
                ('hvie_aper1', models.TimeField()),
                ('hvie_cie1', models.TimeField()),
                ('hvie_aper2', models.TimeField(null=True)),
                ('hvie_cie2', models.TimeField(null=True)),
                ('hsab_aper1', models.TimeField()),
                ('hsab_cie1', models.TimeField()),
                ('hsab_aper2', models.TimeField(null=True)),
                ('hsab_cie2', models.TimeField(null=True)),
                ('hdom_aper1', models.TimeField()),
                ('hdom_cie1', models.TimeField()),
                ('hdom_aper2', models.TimeField(null=True)),
                ('hdom_cie2', models.TimeField(null=True)),
                ('sed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_ecove.tienda')),
            ],
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_ecove.orden'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_ecove.productos'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='tienda_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_ecove.tienda'),
        ),
        migrations.AddField(
            model_name='categorias',
            name='sed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='api_ecove.tienda'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_ecove.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission'),
        ),
    ]
